# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
