# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0002_auto_20160311_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='value',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
