# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0005_build'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='pull_request_id',
        ),
        migrations.RemoveField(
            model_name='build',
            name='pull_request_number',
        ),
        migrations.AddField(
            model_name='build',
            name='pusher_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
