# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0006_auto_20160313_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='build',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildservice.Repository'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildservice.Repository'),
        ),
    ]
