# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0008_auto_20160327_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='branch',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
