# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0010_build_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(default=b'master', max_length=255),
        ),
    ]
