# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildservice', '0012_auto_20160408_0518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([('repository', 'number')]),
        ),
    ]
